#ifndef IRODS_GENQUERY2_DRIVER_HPP
#define IRODS_GENQUERY2_DRIVER_HPP

#include "irods/genquery2_scanner.hpp"
#include "irods/genquery2_ast_types.hpp" // For irods::experimental::api::genquery::select.

#include "parser.hpp" // Generated by Bison.

#ifndef yyFlexLexerOnce
#  include <FlexLexer.h>
#endif // yyFlexLexerOnce

#include <string>

// Give the expected function signature of the yylex() function to flex.
// The parameter, drv, is required. It is referenced by the flex script, lexer.l.
// This is an easy alternative to the "%code provides" directive in parser.y.
//#undef  YY_DECL
//#define YY_DECL yy::parser::symbol_type scanner::yylex(irods::experimental::genquery2::driver& drv)

namespace irods::experimental::genquery2
{
	class driver
	{
	  public:
		driver() = default;

		auto parse(const std::string& _s) -> int;

		irods::experimental::api::genquery::select select;
		scanner lexer;
		yy::location location;
	}; // class driver
} // namespace irods::experimental::genquery2

#endif // IRODS_GENQUERY2_DRIVER_HPP
